(ns compute.kstreamj.dsl)

(defprotocol StreamsBuilder
  (stream [this topics])
  (add-state-store [this supplier]))

(defprotocol Stream
  (filter [this pred])
  (filter-not [this pred])
  (map [this kvm])
  (map-values [this vm])
  (flat-map [this kvm])
  (flat-map-values [this vm])
  (print [this printed])
  (foreach [this action])
  (peek [this action])
  (branch [this preds])
  (merge [this s])
  (through [this topic])
  (through [this topic produced])
  (to [this topic])
  (to [this topic produced])
  (transform [this ts])
  (transform [this ts store-names])
  (transform-values [this vts])
  (transform-values [this vts store-names])
  (process [this ps])
  (process [this ps store-names])
  (group-by-key [this])
  (group-by-key [this serialized])
  (group-by [this kvm])
  (group-by [this kvm serialized])
  (join [this stream-or-table value-joiner join-windows])
  (join [this stream-or-table value-joiner join-windows joined])
  (left-join [this stream-or-table value-joiner join-windows])
  (left-join [this stream-or-table value-joiner join-windows joined])
  (outer-join [this stream- value-joiner join-windows])
  (outer-join [this stream value-joiner join-windows joined]))

(defprotocol GroupedStream
  (count [this])
  (count [this materialized])
  (reduce [this r])
  (reduce [this r materialized])
  (aggregate [this init agg])
  (aggregate [this init agg materialized])
  (windowed-by [this windows]))

(defprotocol TimeWindowedStream
  (count [this])
  (count [this materialized])
  (reduce [this r])
  (reduce [this r materialized])
  (aggregate [this init agg])
  (aggregate [this init agg materialized]))

(defprotocol SessionWindowedStream
  (count [this])
  (count [this materialized])
  (reduce [this r])
  (reduce [this r materialized])
  (aggregate [this init agg merg])
  (aggregate [this init agg merg materialized]))

(defprotocol Table
  (filter [this pred])
  (filter [this pred materialized])
  (filter-not [this pred])
  (filter-not [this pred materialized])
  (map-values [this vm])
  (map-values [this vm materialized])
  (to-stream [this])
  (to-stream [this kvm])
  (transform-values [this vts])
  (transform-values [this vts materialized])
  (group-by [this kvm])
  (group-by [this kvm serialized])
  (join [this table value-joiner])
  (join [this table value-joiner materialized])
  (left-join [this table value-joiner])
  (left-join [this table value-joiner materialized])
  (outer-join [this table value-joiner])
  (outer-join [this table value-joiner materialized]))

(defprotocol GroupedTable
  (count [this])
  (count [this materialized])
  (reduce [this r-add r-sub])
  (reduce [this r-add r-sub materialized])
  (aggregate [this init agg-add agg-sub])
  (aggregate [this init agg-add agg-sub materialized]))